[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/v1/registry"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
